---
- name: Verify
  hosts: all
  gather_facts: no
  become: no

  tasks:
    - name: test connection
      ping:

    # - name: try the package module
    #   package:
    #     name: "{{ molecule_test_httpd_package }}"
    #     state: present
    #   changed_when: no

    - name: "verify web page content"
      uri:
        url: "http://127.0.0.1/"
        status_code: 200
        return_content: yes
      register: result
      failed_when: "'Hello world!' not in result.content"
